export const LOAD_PHONE_LIST_INIT = 'LOAD_PHONE_LIST_START';
export const LOAD_PHONE_LIST_SUCCESS = 'LOAD_PHONE_LIST_SUCCESS';
export const LOAD_PHONE_LIST_FAILED = 'LOAD_PHONE_LIST_FAILED';

export const ADD_CONTACT_INIT = 'ADD_CONTACT_START';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILED = 'ADD_CONTACT_FAILED';

export const EDIT_CONTACT = 'EDIT_CONTACT';

export const DELETE_CONTACT_INIT = 'DELETE_CONTACT_INIT';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';

export const UPDATE_CONTACT_INIT = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';

export const SEARCH_PHONE = 'SEARCH_PHONE';