export const LOAD_PHONE_LIST_START = 'LOAD_PHONE_LIST_START';
export const LOAD_PHONE_LIST_SUCCESS = 'LOAD_PHONE_LIST_SUCCESS';
export const LOAD_PHONE_LIST_FAILED = 'LOAD_PHONE_LIST_FAILED';

export const ADD_CONTACT_START = 'ADD_CONTACT_START';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILED = 'ADD_CONTACT_FAILED';



export const SEARCH_PHONE = 'SEARCH_PHONE';
export const VIEW_ALL_PHONES = 'VIEW_ALL_PHONES';

