export const LOAD_PHONE_LIST_START = 'LOAD_PHONE_LIST_START';
export const LOAD_PHONE_LIST_SUCCESS = 'LOAD_PHONE_LIST_SUCCESS';
export const LOAD_PHONE_LIST_FAILED = 'LOAD_PHONE_LIST_FAILED';

export const SEARCH_PHONE = 'SEARCH_PHONE';
export const VIEW_ALL = 'VIEW_ALL';

